## **AutoML com H2o**

In [1]:
import h2o
from h2o.automl import H2OAutoML
import pandas as pd

In [2]:
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "17.0.18" 2026-01-20; OpenJDK Runtime Environment (build 17.0.18+8-Ubuntu-1); OpenJDK 64-Bit Server VM (build 17.0.18+8-Ubuntu-1, mixed mode, sharing)
  Starting server from /home/joao-inac-io/AutoML-com--Python/.venv/lib/python3.10/site-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmpqmcvvfnx
  JVM stdout: /tmp/tmpqmcvvfnx/h2o_joao_inac_io_started_from_python.out
  JVM stderr: /tmp/tmpqmcvvfnx/h2o_joao_inac_io_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------
H2O_cluster_uptime:         04 secs
H2O_cluster_timezone:       America/Fortaleza
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.10
H2O_cluster_version_age:    1 month and 28 days
H2O_cluster_name:           H2O_from_python_joao_inac_io_0qhr54
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    4.727 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.10.20 final
--------------------------  -----------------------------------

In [3]:
df = pd.read_csv("../data/Churn_treino.csv", sep=";")
df = h2o.H2OFrame(df)
df

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  CreditScore  Geography    Gender      Age    Tenure      Balance    NumOfProducts    HasCrCard    IsActiveMember    EstimatedSalary    Exited
-------------  -----------  --------  -----  --------  -----------  ---------------  -----------  ----------------  -----------------  --------
          619  France       Female       42         2  0                          1            1                 1        1.01349e+07         1
          608  Spain        Female       41         1  8.38079e+06                1            0                 1        1.12543e+07         0
          502  France       Female       42         8  1.59661e+06                3            1                 0        1.13932e+07         1
          699  France       Female       39         1  0                          2            0                 0        9.38266e+06         0
          850  Spain        Female       43         2  1.25511e+07                1            1                 1   790841                   0
          645  Spain        Male         44         8  1.13756e+07                2            1                 0        1.49757e+07         1
          822  France       Male         50         7  0                          2            1                 1   100628                   0
          376  Germany      Female       29         4  1.15047e+07                4            1                 0        1.19347e+07         1
          501  France       Male         44         4  1.42051e+07                2            0                 1   749405                   0
          684  France       Male         27         2  1.34604e+07                1            1                 1        7.17257e+06         0
[10000 rows x 11 columns]

In [4]:
treino, teste = df.split_frame(ratios=[0.7])

In [5]:
treino["Exited"] = treino["Exited"].asfactor()
teste["Exited"] = teste["Exited"].asfactor()

In [6]:
modelo = H2OAutoML(max_runtime_secs=180)
modelo.train(y="Exited", training_frame=treino)

AutoML progress: |███████████████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OStackedEnsembleEstimator : Stacked Ensemble
Model Key: StackedEnsemble_AllModels_2_AutoML_1_20260510_182836


Model Summary for Stacked Ensemble:
key                                        value
-----------------------------------------  ----------------
Stacking strategy                          cross_validation
Number of base models (used / total)       7/12
# GBM base models (used / total)           3/5
# XGBoost base models (used / total)       2/3
# DeepLearning base models (used / total)  1/1
# DRF base models (used / total)           1/2
# GLM base models (used / total)           0/1
Metalearner algorithm                      GLM
Metalearner fold assignment scheme         Random
Metalearner nfolds                         5
Metalearner fold_column
Custom metalearner hyperparameters         None

ModelMetricsBinomialGLM: stackedensemble
** Reported on train data. **

MSE: 0.0795805356106666
RMSE: 0.2821002226349114
LogLoss: 0.26581045775578915
AUC: 0.9287243792264159
AUCPR: 0.8245703925110959
Gini: 0.8574487584528319
Null degrees of freedom: 7005
Residual degrees of freedom: 6998
Null deviance: 7112.469737323272
Residual deviance: 3724.536134074119
AIC: 3740.536134074119

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.279167329905224
       0     1     Error    Rate
-----  ----  ----  -------  --------------
0      5070  498   0.0894   (498.0/5568.0)
1      341   1097  0.2371   (341.0/1438.0)
Total  5411  1595  0.1198   (839.0/7006.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.279167     0.723376  210
max f2                       0.182947     0.781563  255
max f0point5                 0.516726     0.787131  130
max accuracy                 0.473046     0.894662  143
max precision                0.994195     1         0
max recall                   0.016658     1         387
max specificity              0.994195     1         0
max absolute_mcc             0.428232     0.653001  157
max min_per_class_accuracy   0.202821     0.845619  245
max mean_per_class_accuracy  0.204431     0.846761  244
max tns                      0.994195     5568      0
max fns                      0.994195     1435      0
max fps                      0.00656054   5568      399
max tps                      0.016658     1438      387
max tnr                      0.994195     1         0
max fnr                      0.994195     0.997914  0
max fpr                      0.00656054   1         399
max tpr                      0.016658     1         387

Gains/Lift Table: Avg response rate: 20,53 %, avg score: 19,95 %
group    cumulative_data_fraction    lower_threshold    lift        cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ----------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0101342                   0.971694           4.87204     4.87204            1                0.982044   1                           0.982044            0.0493741       0.0493741                  387.204   387.204            0.0493741
2        0.0201256                   0.945776           4.87204     4.87204            1                0.958305   1                           0.970259            0.0486787       0.0980529                  387.204   387.204            0.0980529
3        0.030117                    0.922657           4.87204     4.87204            1                0.93424    1                           0.958309            0.0486787       0.146732                   387.204   387.204            0.146732
4        0.0401085                   0.888506           4.87204     4.87204            1                0.907178   1                           0.945572            0.0486787       0.19541                    387.204   387.204            0.19541
5        0.0500999                   0.851996           4.73284     4.84428            0.971429         0.869281   0.994302                    0.930357            0.0472879       0.242698                   373.284   384.428            0.242339
6        0.100057                    0.603134           4.25956     4.55234            0.874286         0.725265   0.934379                    0.827957            0.212796        0.455494                   325.956   355.234            0.447232
7        0.150014                    0.439788           3.00675     4.03763            0.617143         0.516584   0.828735                    0.724265            0.150209        0.605702                   200.675   303.763            0.573375
8        0.200114                    0.329624           2.05431     3.54109            0.421652         0.381487   0.726819                    0.638448            0.102921        0.708623                   105.431   254.109            0.639837
9        0.300029                    0.198185           1.41985     2.83469            0.291429         0.253081   0.581827                    0.510115            0.141864        0.850487                   41.9853   183.469            0.69262
10       0.400086                    0.127473           0.715864    2.30479            0.146933         0.160178   0.473065                    0.422599            0.0716273       0.922114                   -28.4136  130.479            0.656848
11       0.5                         0.0889129          0.368883    1.91794            0.0757143        0.106586   0.393663                    0.359451            0.0368567       0.958971                   -63.1117  91.7942            0.577505
12       0.600057                    0.062086           0.208504    1.6329             0.042796         0.0745806  0.335157                    0.31195             0.0208623       0.979833                   -79.1496  63.29              0.477858
13       0.699971                    0.0430127          0.111361    1.41571            0.0228571        0.0521351  0.290579                    0.274864            0.0111266       0.99096                    -88.8639  41.5714            0.366139
14       0.800029                    0.0288156          0.0695013   1.24735            0.0142653        0.0352646  0.256021                    0.244898            0.0069541       0.997914                   -93.0499  24.7348            0.248991
15       0.899943                    0.0173536          0.0139201   1.11041            0.00285714       0.0229131  0.227914                    0.220252            0.00139082      0.999305                   -98.608   11.0409            0.125023
16       1                           0.00544305         0.00695013  1                  0.00142653       0.0125868  0.205253                    0.199474            0.00069541      1                          -99.305   0                  0

ModelMetricsBinomialGLM: stackedensemble
** Reported on cross-validation data. **

MSE: 0.10365702235273652
RMSE: 0.3219581065181253
LogLoss: 0.3408249606675487
AUC: 0.8588443874594345
AUCPR: 0.6969478317429136
Gini: 0.717688774918869
Null degrees of freedom: 7005
Residual degrees of freedom: 6998
Null deviance: 7115.06907547985
Residual deviance: 4775.639348873692
AIC: 4791.639348873692

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.28660568693523003
       0     1     Error    Rate
-----  ----  ----  -------  ---------------
0      4912  656   0.1178   (656.0/5568.0)
1      491   947   0.3414   (491.0/1438.0)
Total  5403  1603  0.1637   (1147.0/7006.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.286606     0.622821  215
max f2                       0.130224     0.696782  296
max f0point5                 0.588684     0.693481  112
max accuracy                 0.512133     0.863974  136
max precision                0.993628     1         0
max recall                   0.00748664   1         398
max specificity              0.993628     1         0
max absolute_mcc             0.487977     0.535936  144
max min_per_class_accuracy   0.180866     0.771372  268
max mean_per_class_accuracy  0.183094     0.773356  267
max tns                      0.993628     5568      0
max fns                      0.993628     1436      0
max fps                      0.00564214   5568      399
max tps                      0.00748664   1438      398
max tnr                      0.993628     1         0
max fnr                      0.993628     0.998609  0
max fpr                      0.00564214   1         399
max tpr                      0.00748664   1         398

Gains/Lift Table: Avg response rate: 20,53 %, avg score: 20,52 %
group    cumulative_data_fraction    lower_threshold    lift       cumulative_lift    response_rate    score      cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  ---------  -----------------  ---------------  ---------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0101342                   0.958139           4.80342    4.80342            0.985915         0.975448   0.985915                    0.975448            0.0486787       0.0486787                  380.342   380.342            0.0484991
2        0.0201256                   0.926237           4.80244    4.80294            0.985714         0.94147    0.985816                    0.95858             0.0479833       0.096662                   380.244   380.294            0.0963028
3        0.030117                    0.900239           4.38484    4.66423            0.9              0.912254   0.957346                    0.943211            0.0438108       0.140473                   338.484   366.423            0.138856
4        0.0401085                   0.866798           4.24564    4.55996            0.871429         0.885633   0.935943                    0.928868            0.04242         0.182893                   324.564   355.996            0.17966
5        0.0500999                   0.834614           4.31524    4.51115            0.885714         0.851862   0.925926                    0.91351             0.0431154       0.226008                   331.524   351.115            0.221339
6        0.100057                    0.600325           3.63315    4.07278            0.745714         0.712971   0.835949                    0.813384            0.181502        0.40751                    263.315   307.278            0.386857
7        0.150014                    0.444894           2.26898    3.47209            0.465714         0.517758   0.712655                    0.714936            0.113352        0.520862                   126.898   247.209            0.466624
8        0.200114                    0.327845           1.7073     3.03026            0.350427         0.383619   0.621969                    0.631988            0.0855355       0.606398                   70.7298   203.026            0.511211
9        0.300029                    0.210308           1.25281    2.43834            0.257143         0.262155   0.500476                    0.508828            0.125174        0.731572                   25.2811   143.834            0.542994
10       0.400086                    0.14238            0.938268   2.06319            0.192582         0.17397    0.423475                    0.425084            0.0938804       0.825452                   -6.17318  106.319            0.535222
11       0.5                         0.101285           0.570725   1.76495            0.117143         0.119763   0.362261                    0.364072            0.0570236       0.882476                   -42.9275  76.4951            0.481254
12       0.600057                    0.0720169          0.458709   1.54714            0.0941512        0.0861475  0.317555                    0.317729            0.0458971       0.928373                   -54.1291  54.7141            0.413107
13       0.699971                    0.0513189          0.327123   1.37299            0.0671429        0.0609149  0.281811                    0.281071            0.0326843       0.961057                   -67.2877  37.2995            0.328514
14       0.800029                    0.0342303          0.180704   1.22388            0.0370899        0.0421986  0.251204                    0.251196            0.0180807       0.979138                   -81.9296  22.3878            0.225366
15       0.899943                    0.0213194          0.132241   1.10268            0.0271429        0.0274597  0.226328                    0.226356            0.0132128       0.99235                    -86.7759  10.2682            0.116273
16       1                           0.00450142         0.0764515  1                  0.0156919        0.0152525  0.205253                    0.205234            0.00764951      1                          -92.3549  0                  0

Cross-Validation Metrics Summary:
                      mean        sd           cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid
--------------------  ----------  -----------  ------------  ------------  ------------  ------------  ------------
accuracy              0.84458095  0.019099902  0.842031      0.85470086    0.8207547     0.8346745     0.8707436
aic                   972.3279    39.49639     999.9398      909.869       1011.5342     974.0014      966.2949
auc                   0.8588965   0.013611793  0.86088187    0.8683189     0.83826286    0.8540202     0.8729988
err                   0.15541907  0.019099902  0.15796897    0.14529915    0.17924528    0.16532554    0.12925643
err_count             217.4       23.233597    224.0         204.0         247.0         226.0         186.0
f0point5              0.6251337   0.052988     0.63439566    0.6113537     0.56477344    0.6065469     0.70859873
f1                    0.62942916  0.027459217  0.65325075    0.62222224    0.5890183     0.6258278     0.65682656
f2                    0.63613254  0.024980221  0.673261      0.6334842     0.6154381     0.6463748     0.61210454
lift_top_group        4.824417    0.37834275   4.3109665     5.3587785     4.9390683     4.7797203     4.7335525
loglikelihood         0.0         0.0          0.0           0.0           0.0           0.0           0.0
---                   ---         ---          ---           ---           ---           ---           ---
mean_per_class_error  0.23063774  0.012524655  0.21395755    0.22755043    0.24876477    0.22924739    0.23366857
mse                   0.10371806  0.005724812  0.1047535     0.09597325    0.11008638    0.107724324   0.10005281
null_deviance         1423.0138   58.08455     1483.3722     1356.1396     1388.5853     1402.52       1484.4519
pr_auc                0.6968995   0.028718075  0.71887016    0.6877127     0.6580415     0.68893737    0.7309357
precision             0.62373275  0.07440158   0.6224189     0.60431653    0.5496894     0.5943396     0.7478992
r2                    0.36336654  0.031376727  0.38245502    0.36770892    0.31824216    0.34888294    0.39954367
recall                0.6418584   0.037596848  0.6872964     0.64122134    0.6344086     0.66083914    0.5855263
residual_deviance     955.12787   39.88045     983.9398      891.869       993.5342      958.0014      948.2949
rmse                  0.32195395  0.008924028  0.32365647    0.3097955     0.33179268    0.32821384    0.31631124
specificity           0.89686614  0.030868722  0.88478845    0.90367776    0.8680619     0.8806661     0.9471366
[24 rows x 8 columns]


[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [7]:
ranking = modelo.leaderboard
ranking = ranking.as_data_frame(use_multi_thread=True)
ranking

Export File progress: |██████████████████████████████████████████████████████████| (done) 100%

,model_id,auc,logloss,aucpr,mean_per_class_error,rmse,mse
0,StackedEnsemble_AllModels_2_AutoML_1_20260510_...,0.858844,0.340825,0.696948,0.229631,0.321958,0.103657
1,StackedEnsemble_AllModels_3_AutoML_1_20260510_...,0.858424,0.340787,0.698441,0.234474,0.321611,0.103434
2,StackedEnsemble_BestOfFamily_3_AutoML_1_202605...,0.858079,0.340985,0.696940,0.231784,0.321875,0.103603
3,GBM_5_AutoML_1_20260510_182836,0.856552,0.343510,0.692164,0.239359,0.322763,0.104176
4,StackedEnsemble_AllModels_1_AutoML_1_20260510_...,0.856196,0.343942,0.692022,0.239554,0.323593,0.104713
5,GBM_grid_1_AutoML_1_20260510_182836_model_5,0.856109,0.347084,0.687426,0.236772,0.325021,0.105639
6,StackedEnsemble_BestOfFamily_2_AutoML_1_202605...,0.855482,0.345406,0.690049,0.229714,0.324353,0.105205
7,StackedEnsemble_BestOfFamily_1_AutoML_1_202605...,0.855247,0.345677,0.689281,0.231406,0.324439,0.105261
8,GBM_grid_1_AutoML_1_20260510_182836_model_6,0.855183,0.347690,0.689832,0.241343,0.325102,0.105691
9,GBM_1_AutoML_1_20260510_182836,0.854820,0.346471,0.689439,0.243777,0.324772,0.105477
10,GBM_2_AutoML_1_20260510_182836,0.852972,0.347168,0.686220,0.243480,0.324647,0.105396
11,GBM_grid_1_AutoML_1_20260510_182836_model_4,0.852164,0.347747,0.685062,0.229755,0.325111,0.105697
12,XGBoost_3_AutoML_1_20260510_182836,0.849771,0.349265,0.686088,0.252240,0.325222,0.105769
13,GBM_grid_1_AutoML_1_20260510_182836_model_2,0.849647,0.350172,0.682132,0.241195,0.326296,0.106469
14,GBM_3_AutoML_1_20260510_182836,0.849126,0.350453,0.681435,0.246754,0.326379,0.106524
15,GBM_grid_1_AutoML_1_20260510_182836_model_1,0.847575,0.354007,0.672023,0.235611,0.328279,0.107767
16,GBM_grid_1_AutoML_1_20260510_182836_model_7,0.845559,0.413972,0.656124,0.235482,0.358255,0.128346
17,XGBoost_1_AutoML_1_20260510_182836,0.843991,0.360271,0.666569,0.234533,0.330850,0.109462
18,XGBoost_grid_1_AutoML_1_20260510_182836_model_1,0.842922,0.360825,0.668887,0.258388,0.331155,0.109664
19,DeepLearning_1_AutoML_1_20260510_182836,0.842652,0.362106,0.661944,0.245789,0.333400,0.111155
20,DeepLearning_grid_1_AutoML_1_20260510_182836_m...,0.841322,0.364744,0.667923,0.241087,0.329980,0.108887
21,GBM_4_AutoML_1_20260510_182836,0.840907,0.358535,0.670143,0.239383,0.330057,0.108937
22,DRF_1_AutoML_1_20260510_182836,0.833934,0.426477,0.656517,0.250102,0.334101,0.111623
23,XGBoost_grid_1_AutoML_1_20260510_182836_model_2,0.831645,0.390401,0.651180,0.262201,0.339853,0.115500
24,GBM_grid_1_AutoML_1_20260510_182836_model_3,0.829996,0.368032,0.655294,0.260454,0.334517,0.111901
25,XGBoost_grid_1_AutoML_1_20260510_182836_model_3,0.829798,0.390587,0.635341,0.260458,0.343400,0.117924
26,XGBoost_2_AutoML_1_20260510_182836,0.828602,0.381590,0.640647,0.265383,0.340356,0.115842
27,DeepLearning_grid_1_AutoML_1_20260510_182836_m...,0.825375,0.392288,0.632390,0.264747,0.345246,0.119195
28,DeepLearning_grid_1_AutoML_1_20260510_182836_m...,0.825176,0.387630,0.622694,0.266216,0.345386,0.119292
29,XRT_1_AutoML_1_20260510_182836,0.815638,0.393108,0.633535,0.257054,0.343994,0.118332
30,GLM_1_AutoML_1_20260510_182836,0.760494,0.434825,0.454261,0.310384,0.371554,0.138052

In [8]:
df_test = pd.read_csv("../data/Churn_teste.csv", sep=";")
df_test = h2o.H2OFrame(teste)

In [9]:
prever = modelo.leader.predict(df_test)
prever = prever.as_data_frame(use_multi_thread=True)
prever

stackedensemble prediction progress: |███████████████████████████████████████████| (done) 100%
Export File progress: |██████████████████████████████████████████████████████████| (done) 100%

      predict        p0        p1
0           0  0.941189  0.058811
1           0  0.892592  0.107408
2           0  0.989695  0.010305
3           0  0.981925  0.018075
4           0  0.977666  0.022334
...       ...       ...       ...
2989        0  0.724747  0.275253
2990        0  0.963648  0.036352
2991        0  0.856080  0.143920
2992        0  0.736438  0.263562
2993        0  0.972816  0.027184

[2994 rows x 3 columns]